//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ПрактикаКатаргинНкикита
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудники
    {
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public string Почта { get; set; }
        public int ID_Сотрудника { get; set; }
        public int Id_отдела { get; set; }
        public Nullable<System.TimeSpan> заблокирован_до { get; set; }
    
        public virtual Отдел Отдел { get; set; }
    }
}
